class HTTPConnection:
    ...
    response_class = HTTPResponse
    ...
    def getresponse(self):
        ...
        response = self.response_class(self.sock, method=self._method)
        ...


class SpecialHTTPConnection(HTTPConnection):
    response_class = SpecialHTTPResponse